services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - APP_USER=${APP_USER}
        - APP_UID=${APP_UID}
        - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    image: ${APP_NAME}_php
    container_name: ${APP_NAME}_php
    restart: unless-stopped
    working_dir: /var/www/personal-site
    volumes:
      - ./:/var/www/personal-site
      - ./docker/php/ini/prod.ini:/usr/local/etc/php/conf.d/php.ini:ro
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - supreme-network
    expose:
      - "9000" # fpm
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      retries: 3
      timeout: 5s

  supervisor:
    build:
      context: .
      dockerfile: docker/supervisor/Dockerfile
      args:
        - SUPERVISOR_USER=${SUPERVISOR_USER}
        - SUPERVISOR_UID=${SUPERVISOR_UID}
    image: ${APP_NAME}_supervisor
    container_name: ${APP_NAME}_supervisor
    restart: unless-stopped
    working_dir: /var/www/personal-site
    volumes:
      - ./:/var/www/personal-site
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - supreme-network
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:1.28.0
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    volumes:
      - ./public:/var/www/personal-site/public
      - ./storage/app/public:/var/www/personal-site/storage/app/public
      - ./docker/nginx/conf.d/production.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - php
    networks:
      - supreme-network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: prod
    image: ${APP_NAME}_node
    container_name: ${APP_NAME}_node
    restart: unless-stopped
    working_dir: /var/www/personal-site
    volumes:
      - ./:/var/www/personal-site
      - node_modules:/var/www/personal-site/node_modules
    networks:
      - supreme-network

  postgres:
    image: postgres:17
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_ENV=${APP_ENV}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      retries: 5
      timeout: 5s
    networks:
      - supreme-network

  mongodb:
    image: mongo:6.0
    container_name: ${APP_NAME}_mongodb
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./docker/mongodb/init_scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_TEST_DB_NAME: ${MONGO_TEST_DB_NAME}
      APP_ENV: ${APP_ENV}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 60s
      retries: 5
      timeout: 5s
    networks:
      - supreme-network

  redis:
    image: redis:7.4.1
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      retries: 5
      timeout: 3s
    networks:
      - supreme-network

networks:
  supreme-network:
    external: true

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  node_modules:
    driver: local
  redis_data:
    driver: local
