services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - APP_USER=${APP_USER}
        - APP_UID=${APP_UID}
        - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    image: ${APP_NAME}_php
    container_name: ${APP_NAME}_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/ini/local.ini:/usr/local/etc/php/conf.d/php.ini:ro
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - supreme-network
    expose:
      - "9000" # fpm
      - "9003" # xdebug
    extra_hosts:
      - "host.docker.internal:host-gateway" # for linux xdebug
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      retries: 3
      timeout: 5s

  supervisor:
    build:
      context: .
      dockerfile: docker/supervisor/Dockerfile
      args:
        - SUPERVISOR_USER=${SUPERVISOR_USER}
        - SUPERVISOR_UID=${SUPERVISOR_UID}
    image: ${APP_NAME}_supervisor
    container_name: ${APP_NAME}_supervisor
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - supreme-network
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:1.30.0
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - "8200:80"
    volumes:
      - ./public:/var/www/personal-site/public
      - ./storage/app/public:/var/www/personal-site/storage/app/public
      - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - php
    networks:
      - supreme-network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: dev
    image: ${APP_NAME}_node
    container_name: ${APP_NAME}_node
    restart: unless-stopped
    ports:
    - "3000:3000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - node_modules:/var/www/node_modules
    networks:
      - supreme-network

  postgres:
    image: postgres:17
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init_scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - supreme-network

  mongodb:
    image: mongo:6.0
    container_name: ${APP_NAME}_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./docker/mongodb/init_scripts:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_TEST_DB_NAME: ${MONGO_TEST_DB_NAME}
      APP_ENV: ${APP_ENV}
    networks:
      - supreme-network

  redis:
    image: redis:7.4
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - supreme-network

networks:
  supreme-network:
    external: true

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  node_modules:
    driver: local
  redis_data:
    driver: local
