<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use App\Models\UserRole;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'login' => fake()->unique()->name(),
            'password' => static::$password ??= Hash::make('password'),
            'role_id' => UserRole::where('title', UserRole::USER)->first()->id,
            'desc' => 'User is generated by factory',
        ];
    }

    public function admin(): static
    {
        return $this->state([
            'role_id' => UserRole::where('title', UserRole::ADMIN)->first()->id,
        ]);
    }
}
