<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;

use App\Models\User;
use App\Models\UserRole;

class UserFactory extends Factory
{
    protected $model = User::class;

    protected static ?string $password;

    public function definition(): array
    {
        return [
            'login' => fake()->unique()->userName(),
            'name' => fake()->name(),
            'password' => static::$password ??= Hash::make('password'),
            'role_id' => UserRole::where('title', UserRole::USER)->first()->id,
            'desc' => 'User is generated by factory',
        ];
    }

    public function admin(): static
    {
        return $this->state([
            'role_id' => UserRole::where('title', UserRole::ADMIN)->first()->id,
        ]);
    }
}
