<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use App\Models\User;
use App\Models\UserRole;

class UserFactory extends Factory
{
    protected $model = User::class;

    public function definition(): array
    {
        return [
            'login' => $this->faker->unique()->userName(),
            'name' => $this->faker->name(),
            'password' => Hash::make(Str::password(14)),
            'role_id' => UserRole::where('title', UserRole::USER)->first()->id,
            'desc' => 'User was generated by factory',
        ];
    }

    public function admin(): static
    {
        return $this->state(function (array $attributes) {
            return [
                'role_id' => UserRole::where('title', UserRole::ADMIN)->first()->id,
            ];
        });
    }
}
