services:
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
        - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    container_name: ${CONTAINER_PHP}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - tisherd_personal_website_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.27.3-alpine
    container_name: ${CONTAINER_NGINX}
    restart: unless-stopped
    volumes:
      - ../:/var/www
    depends_on:
      - php
    networks:
      - tisherd_personal_website_network

  node:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: ${CONTAINER_NODE}
    restart: on-failure
    ports:
    - "3000:3000"
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - /var/www/node_modules
    networks:
      - tisherd_personal_website_network

  postgres:
    image: postgres:17
    container_name: ${CONTAINER_POSTGRES}
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - tisherd_personal_website_postgres_data:/var/lib/postgresql/data
      - ./postgres/init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_ENV=${APP_ENV}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      retries: 5
      timeout: 5s
    networks:
      - tisherd_personal_website_network

  mongodb:
    image: mongo:6.0
    container_name: ${CONTAINER_MONGODB}
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - tisherd_personal_website_mongodb_data:/data/db
      - ./mongodb/init_scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_TEST_DB_NAME: ${MONGO_TEST_DB_NAME}
      APP_ENV: ${APP_ENV}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 60s
      retries: 5
      timeout: 5s
    networks:
      - tisherd_personal_website_network

  redis:
    image: redis:7.4.1
    container_name: ${CONTAINER_REDIS}
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      retries: 5
      timeout: 3s
    networks:
      - tisherd_personal_website_network

networks:
  tisherd_personal_website_network:
    driver: bridge

volumes:
  tisherd_personal_website_postgres_data:
    driver: local
  tisherd_personal_website_mongodb_data:
    driver: local
